name: CMake

on:
  push:

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: "Build and Render"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v5
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        if: runner.os == 'Windows'
        with:
          arch: x64

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S "${{ github.workspace }}" \
            -B "${{ runner.workspace }}/build" \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_INSTALL_PREFIX="${{ runner.workspace }}/install"

      - name: Build
        shell: bash
        run: cmake --build "${{ runner.workspace }}/build" --config ${{ env.BUILD_TYPE }}

      - name: Install
        shell: bash
        run: cmake --install "${{ runner.workspace }}/build" --config ${{ env.BUILD_TYPE }}

      - name: Render Sample Image
        shell: bash
        working-directory: ${{ runner.workspace }}/install/bin
        run: |
          BIN=$(find . -name "ray_tracing_one_week*" | head -1)
          "$BIN" --verbose -t 2 --width 300 --height 200 -s 100 --scene metal_test "${{ runner.workspace }}/sample_image.ppm"

      - name: Upload Sample Image
        uses: actions/upload-artifact@v6
        with:
          name: sample_image_${{ matrix.os }}
          path: ${{ runner.workspace }}/sample_image.ppm

      - name: Upload Binary
        uses: actions/upload-artifact@v6
        with:
          name: ray_tracing_one_week-${{ matrix.os }}
          path: ${{ runner.workspace }}/install/bin/